-- MySQL Script generated by MySQL Workbench
-- 08/12/22 06:27:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema athletica_old
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema athletica2
-- -----------------------------------------------------
-- New athletica database
-- -----------------------------------------------------
-- Schema athletica2_admin
-- -----------------------------------------------------
-- Add here the following tables:
-- -  all the base-data tables like licensed athletes, clubs, team and their performances --> this data will be copied to the specific meeting-DB as soon as an athlete/club/team is registered
-- -  probably add here a table for user accounts, when they shall be local and not transferred to slaves; so far the local admin account is simply set in a config file.
-- -----------------------------------------------------
-- Schema athletica3
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baseSUI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `athletes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `athletes` (
  `license` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `licensePaid` TINYINT(1) NOT NULL DEFAULT 1,
  `licenseCategory` VARCHAR(4) NOT NULL DEFAULT '',
  `lastname` VARCHAR(100) NOT NULL DEFAULT '',
  `firstname` VARCHAR(100) NOT NULL DEFAULT '',
  `sex` ENUM('m', 'f') NOT NULL DEFAULT 'm',
  `nationality` CHAR(3) NOT NULL DEFAULT '',
  `clubCode` VARCHAR(30) NOT NULL DEFAULT '',
  `birthdate` DATE NOT NULL DEFAULT '1900-01-01',
  PRIMARY KEY (`license`))
ENGINE = InnoDB
COMMENT = 'on purpose not linked to clubs to allow that the data is not written in the \"right\" order';


-- -----------------------------------------------------
-- Table `clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs` (
  `code` VARCHAR(30) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `short` VARCHAR(255) NOT NULL DEFAULT '',
  `type` VARCHAR(100) NOT NULL DEFAULT '',
  `lg` VARCHAR(100) NOT NULL DEFAULT '',
  INDEX `account_code` (`code` ASC),
  UNIQUE INDEX `account_code_UNIQUE` (`code` ASC),
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `performances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `performances` (
  `license` INT UNSIGNED NOT NULL,
  `discipline` INT UNSIGNED NOT NULL COMMENT 'ATTENTION: this is not the same ID as in the competition DB. There will have to be a translation function for baseDisciplineIDs to liveAthleteicsIDs',
  `bestEffort` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'personal best\ntranslation to the internal datatype will be done on request. This is probably more efficient then translating during baseDataUpdates, since most of the base data will never be used until it is updated again.',
  `bestEffortDate` DATE NOT NULL DEFAULT '1900-01-01',
  `bestEffortEvent` VARCHAR(100) NOT NULL DEFAULT '',
  `seasonEffort` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'seasonal best: relly just the current season (probably even correctly indoor/outdoor separated)\ntranslation to the internal datatype will be done on request. This is probably more efficient then translating during baseDataUpdates, since most of the base data will never be used until it is updated again.',
  `seasonEffortDate` DATE NOT NULL DEFAULT '1900-01-01',
  `seasonEffortEvent` VARCHAR(100) NOT NULL DEFAULT '',
  `notificationEffort` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'notification effort: the best of the last two years, including indoor and outdoor in the same field (at least in 2020 the data was provided like this by alabus)\ntranslation to the internal datatype will be done on request. This is probably more efficient then translating during baseDataUpdates, since most of the base data will never be used until it is updated again.',
  `notificationEffortDate` DATE NOT NULL DEFAULT '1900-01-01',
  `notificationEffortEvent` VARCHAR(100) NOT NULL DEFAULT '',
  `season` ENUM('I', 'O') NOT NULL DEFAULT 'O',
  PRIMARY KEY (`license`, `discipline`, `season`))
ENGINE = InnoDB
COMMENT = 'on purpose not linked to athletes to allow that the data is not written in the \"right\" order';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
